name: Deploy Backend with UUID Fix (DISABLED - use deploy-backend.yml instead)

on:
  # This workflow is disabled - use deploy-backend.yml instead
  workflow_dispatch:
    inputs:
      disabled:
        description: 'This workflow is disabled'
        required: false
        default: 'true'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    if: false  # This workflow is disabled

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: activitytrackeracr.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
    
    - name: Build and push Docker image
      run: |
        cd activity-tracker/backend
        docker build --platform linux/amd64 -f Dockerfile.complete -t activitytrackeracr.azurecr.io/activity-tracker-backend:v17 .
        docker push activitytrackeracr.azurecr.io/activity-tracker-backend:v17
    
    - name: Azure CLI Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Deploy to Azure Container Apps
      run: |
        az containerapp update \
          --name activity-tracker-backend \
          --resource-group activity-tracker-rg \
          --image activitytrackeracr.azurecr.io/activity-tracker-backend:v17
